export default defineEventHandler((event) => {
  return {
    marques: [
      { id: 1, marque: "ABARTH" },
      { id: 2, marque: "AIWAYS" },
      { id: 3, marque: "ALEKO" },
      { id: 4, marque: "ALFA ROMEO" },
      { id: 5, marque: "ALPINE RENAULT" },
      { id: 6, marque: "ARO" },
      { id: 7, marque: "ASIA" },
      { id: 8, marque: "ASTON MARTIN" },
      { id: 9, marque: "AUDI" },
      { id: 10, marque: "AUSTIN" },
      { id: 11, marque: "AUTOBIANCHI" },
      { id: 12, marque: "AUVERLAND" },
      { id: 13, marque: "BEDFORD" },
      { id: 14, marque: "BEE BEE AUTOMOTIVE" },
      { id: 15, marque: "BENTLEY" },
      { id: 16, marque: "BERTONE" },
      { id: 17, marque: "BMW" },
      { id: 18, marque: "BUICK" },
      { id: 19, marque: "BYD" },
      { id: 20, marque: "CADILLAC" },
      { id: 21, marque: "CHEVROLET" },
      { id: 22, marque: "CHRYSLER" },
      { id: 23, marque: "CITROEN" },
      { id: 24, marque: "COURB" },
      { id: 25, marque: "CUPRA" },
      { id: 26, marque: "DACIA" },
      { id: 27, marque: "DAEWOO" },
      { id: 28, marque: "DAF" },
      { id: 29, marque: "DAIHATSU" },
      { id: 30, marque: "DAIMLER" },
      { id: 31, marque: "DATSUN" },
      { id: 32, marque: "DODGE" },
      { id: 33, marque: "DS" },
      { id: 34, marque: "EBRO" },
      { id: 35, marque: "FERRARI" },
      { id: 36, marque: "FEST" },
      { id: 37, marque: "FIAT" },
      { id: 38, marque: "FISKER" },
      { id: 39, marque: "FORD" },
      { id: 40, marque: "FSO-POLSKI" },
      { id: 41, marque: "GAC GONOW" },
      { id: 42, marque: "GME" },
      { id: 43, marque: "GRANDIN" },
      { id: 44, marque: "HONDA" },
      { id: 45, marque: "HONGQI" },
      { id: 46, marque: "HYUNDAI" },
      { id: 47, marque: "INEOS" },
      { id: 48, marque: "INFINITI" },
      { id: 49, marque: "INNOCENTI" },
      { id: 50, marque: "ISUZU" },
      { id: 51, marque: "IVECO" },
      { id: 52, marque: "JAGUAR" },
      { id: 53, marque: "JEEP" },
      { id: 54, marque: "KIA" },
      { id: 55, marque: "LADA" },
      { id: 56, marque: "LANCIA" },
      { id: 57, marque: "LAND ROVER" },
      { id: 58, marque: "LDV" },
      { id: 59, marque: "LEAPMOTOR" },
      { id: 60, marque: "LEXUS" },
      { id: 61, marque: "LOTUS" },
      { id: 62, marque: "LYNK&CO" },
      { id: 63, marque: "MAHINDRA" },
      { id: 64, marque: "MAN" },
      { id: 65, marque: "MARUTI" },
      { id: 66, marque: "MASERATI" },
      { id: 67, marque: "MATRA" },
      { id: 68, marque: "MAXUS" },
      { id: 69, marque: "MAZDA" },
      { id: 70, marque: "MCC" },
      { id: 71, marque: "MEGA" },
      { id: 72, marque: "MERCEDES" },
      { id: 73, marque: "MG" },
      { id: 74, marque: "MIA" },
      { id: 75, marque: "MINI" },
      { id: 76, marque: "MITSUBISHI" },
      { id: 77, marque: "MPM MOTORS" },
      { id: 78, marque: "NISSAN" },
      { id: 79, marque: "OPEL" },
      { id: 80, marque: "PANHARD" },
      { id: 81, marque: "PEUGEOT" },
      { id: 82, marque: "PIAGGIO" },
      { id: 83, marque: "PONTIAC" },
      { id: 84, marque: "PORSCHE" },
      { id: 85, marque: "PROTON" },
      { id: 86, marque: "RENAULT" },
      { id: 87, marque: "ROVER" },
      { id: 88, marque: "SAAB" },
      { id: 89, marque: "SANTANA" },
      { id: 90, marque: "SEAT" },
      { id: 91, marque: "SERES DFSK" },
      { id: 92, marque: "SKODA" },
      { id: 93, marque: "SMART" },
      { id: 94, marque: "SSANGYONG" },
      { id: 95, marque: "SUBARU" },
      { id: 96, marque: "SUNBEAM" },
      { id: 97, marque: "SUZUKI" },
      { id: 98, marque: "TALBOT" },
      { id: 99, marque: "TATA" },
      { id: 100, marque: "TESLA" },
      { id: 101, marque: "THINK" },
      { id: 102, marque: "TOYOTA" },
      { id: 103, marque: "TRIUMPH" },
      { id: 104, marque: "UMM" },
      { id: 105, marque: "VINFAST" },
      { id: 106, marque: "VOLKSWAGEN" },
      { id: 107, marque: "VOLVO" },
      { id: 108, marque: "XPENG" },
      { id: 109, marque: "ZASTAVA" },
      { id: 110, marque: "ZAZ" },
    ],
  };
});
